service: serverless-graphql-appsync-es

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

custom:
  accountId: 1234xxxxxxxx # replace this with your accountId
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Users
            sources: [seed-data/Users.json]
  appSync:
    # name:  # defaults to api
    # apiId # only required for update-appsync
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-east-1 # required # region
      defaultAction: ALLOW
      userPoolId: us-east-1_xxxxxxxxx # replace this with your Cognito User Pool Id
    # region: # defaults to provider region
    # mappingTemplatesLocation: # defaults to mapping-templates
    mappingTemplates:
      - dataSource: Users
        type: Query
        field: getUserInfo
        request: "getUserInfo-request-mapping-template.txt"
        response: "getUserInfo-response-mapping-template.txt"
      - dataSource: Users
        type: Query
        field: meInfo
        request: "meInfo-request-mapping-template.txt"
        response: "meInfo-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: User
        field: topTweet
        request: "topTweet-request-mapping-template.txt"
        response: "topTweet-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: User
        field: tweets
        request: "tweets-request-mapping-template.txt"
        response: "tweets-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: Mutation
        field: createTweet
        request: "createTweet-request-mapping-template.txt"
        response: "createTweet-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: Mutation
        field: deleteTweet
        request: "deleteTweet-request-mapping-template.txt"
        response: "deleteTweet-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: Mutation
        field: reTweet
        request: "reTweet-request-mapping-template.txt"
        response: "reTweet-response-mapping-template.txt"
      - dataSource: ElasticSearch
        type: Mutation
        field: updateTweet
        request: "updateTweet-request-mapping-template.txt"
        response: "updateTweet-response-mapping-template.txt"
      - dataSource: Users
        type: Mutation
        field: updateUserInfo
        request: "updateUserInfo-request-mapping-template.txt"
        response: "updateUserInfo-response-mapping-template.txt"
    # schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: 'Users'
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Dynamo-${self:custom.appSync.serviceRole}"
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearch
        description: 'ElasticSearch'
        config:
          endpoint: # required # "https://{DOMAIN}.{REGION}.es.amazonaws.com"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/ElasticSearch-${self:custom.appSync.serviceRole}"

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          -
            AttributeName: handle
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: handle
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: 'ESUsers'
    AppSyncESServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "AppSyncESServiceRoleRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "AppSyncESServiceRolePolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "es:*"
                  Resource:
                    - "arn:aws:es:us-east-1:*:domain/appsync/*"
    AppSyncDynamoDBServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "AppSyncDynamoDBServiceRoleRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "AppSyncDynamoDBServiceRolePolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "arn:aws:dynamodb:us-east-1:*:table/ESUsers"
                    - "arn:aws:dynamodb:us-east-1:*:table/ESUsers/*"
