service: serverless-graphql-appsync-dynamo

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-appsync-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: Users
            sources: [seed-data/Users.json]
          - table: Tweets
            sources: [seed-data/Tweets.json]
  appSync:
    name:  "dynamoGraphqlApi"
    # apiId # only required for update-appsync/delete-appsync
    authenticationType: "AMAZON_COGNITO_USER_POOLS"
    userPoolConfig:
      awsRegion: "us-east-1" # required # region
      defaultAction: "ALLOW"
      userPoolId: "us-east-1_dplcfGDHn" # required # user pool ID
      region: "us-east-1" # defaults to provider region
    mappingTemplatesLocation: "mapping-templates" # defaults to mapping-templates
    mappingTemplates:
      - dataSource: "Users" # data source name
        type: "Query"
        field: "getUserInfo"
        request: "getUserInfo-request-mapping-template.txt" # request mapping template name
        response: "getUserInfo-response-mapping-template.txt" # response mapping template name
      - dataSource: "Tweets" # data source name
        type: "User"
        field: "topTweet"
        request: "topTweet-request-mapping-template.txt" # request mapping template name
        response: "topTweet-response-mapping-template.txt" # response mapping template name
    schema: "schema.graphql" # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: "AMAZON_DYNAMODB"
        name: "Users" # data source name
        description: "User info" # DynamoDB Table Description
        config:
          tableName: "Users" # DynamoDB Table Name
          serviceRoleArn: "arn:aws:iam::*:role/dynamo-${self:custom.appSync.serviceRole}"
      - type: "AMAZON_DYNAMODB"
        name: "Tweets" # data source name
        description: "Tweets info" # DynamoDB Table Description
        config:
          tableName: "Tweets" # DynamoDB Table Name
          serviceRoleArn: "arn:aws:iam::*:role/dynamo-${self:custom.appSync.serviceRole}"

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          -
            AttributeName: handle
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: handle
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: "Users"
    TweetsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          -
            AttributeName: tweet_id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: tweet_id
            AttributeType: S
          -
            AttributeName: handle
            AttributeType: S
          -
            AttributeName: retweet_count
            AttributeType: N
          -
            AttributeName: created_at
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: "Tweets"
        GlobalSecondaryIndexes:
          -
            IndexName: top-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: retweet_count
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 50
              WriteCapacityUnits: 50
          -
            IndexName: tweet-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 50
              WriteCapacityUnits: 50
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "arn:aws:dynamodb:us-east-1:*:table/Users"
                    - "arn:aws:dynamodb:us-east-1:*:table/Users/*"
                    - "arn:aws:dynamodb:us-east-1:*:table/Tweets"
                    - "arn:aws:dynamodb:us-east-1:*:table/Tweets/*"