export { default as alcohol } from '../../assets/icons/001-alcohol.png';
export { default as babyProducts } from '../../assets/icons/002-baby products.png';
export { default as sweets } from '../../assets/icons/003-sweets.png';
export { default as barcode } from '../../assets/icons/004-barcode.png';
export { default as basket } from '../../assets/icons/005-basket.png';
export { default as bill } from '../../assets/icons/006-bill.png';
export { default as bread } from '../../assets/icons/007-bread.png';
export { default as butter } from '../../assets/icons/008-Butter.png';
export { default as cannedFood } from '../../assets/icons/009-canned food.png';
export { default as swipeCard } from '../../assets/icons/010-swipe card.png';
export { default as cart } from '../../assets/icons/011-cart.png';
export { default as cashRegister } from '../../assets/icons/012-cash register.png';
export { default as cashRegister1 } from '../../assets/icons/013-cash register.png';
export { default as cashier } from '../../assets/icons/014-cashier.png';
export { default as cereal } from '../../assets/icons/015-cereal.png';
export { default as cheeses } from '../../assets/icons/016-cheeses.png';
export { default as cleaningProducts } from '../../assets/icons/017-cleaning products.png';
export { default as fashion } from '../../assets/icons/018-fashion.png';
export { default as coffee } from '../../assets/icons/019-coffee.png';
export { default as cosmetics } from '../../assets/icons/020-cosmetics.png';
export { default as coupon } from '../../assets/icons/021-coupon.png';
export { default as softdrinks } from '../../assets/icons/022-softdrinks.png';
export { default as egg } from '../../assets/icons/023-egg.png';
export { default as flour } from '../../assets/icons/024-flour.png';
export { default as forklift } from '../../assets/icons/025-forklift.png';
export { default as frozenGoods } from '../../assets/icons/026-frozen goods.png';
export { default as fruits } from '../../assets/icons/027-fruits.png';
export { default as shoppingOnline } from '../../assets/icons/028-shopping online.png';
export { default as shopping } from '../../assets/icons/029-shopping.png';
export { default as groceryCart } from '../../assets/icons/030-grocery cart.png';
export { default as shopping1 } from '../../assets/icons/031-shopping.png';
export { default as scale } from '../../assets/icons/032-scale.png';
export { default as sauces } from '../../assets/icons/033-sauces.png';
export { default as kitchenTools } from '../../assets/icons/034-kitchen tools.png';
export { default as meat } from '../../assets/icons/035-meat.png';
export { default as milk } from '../../assets/icons/036-milk.png';
export { default as oil } from '../../assets/icons/037-oil.png';
export { default as pasta } from '../../assets/icons/038-pasta.png';
export { default as scanner } from '../../assets/icons/039-scanner.png';
export { default as petFood } from '../../assets/icons/040-pet food.png';
export { default as pizza } from '../../assets/icons/041-pizza.png';
export { default as sausages } from '../../assets/icons/042-sausages.png';
export { default as seafood } from '../../assets/icons/043-seafood.png';
export { default as store } from '../../assets/icons/044-store.png';
export { default as supplementaryFood } from '../../assets/icons/045-supplementary food.png';
export { default as snacks } from '../../assets/icons/046-snacks.png';
export { default as toiletries } from '../../assets/icons/047-toiletries.png';
export { default as toys } from '../../assets/icons/048-toys.png';
export { default as vegetables } from '../../assets/icons/049-vegetables.png';
export { default as water } from '../../assets/icons/050-water.png';
