type PlaceLocation {
  latitude: Float
  longitude: Float
}

type BusinessHours {
  start: String
  end: String
  weekday: String
}

type PlaceOverview {
  name: String!
  bio: String
  category: String!
  location: PlaceLocation!
  containing: Boolean
  otherLocation: PlaceLocation
  hours: [BusinessHours!]
  facebookUrl: String
  orderUrl: String
  ownership: Boolean
}

type PlaceFarmShares {}

type PlaceFarm {}

type PlaceFoodCoOp {}

type PlaceGroceries {}

type PlaceFarmStand {}

type PlaceFarmerMarket {}

input PlaceInput {
  overview: PlaceOverview!
  farmShares: PlaceFarmShares
  farm: PlaceFarm
  foodCoOp: PlaceFoodCoOp
  groceries: PlaceGroceries
  farmStand: PlaceFarmStand
  farmerMarket: PlaceFarmerMarket
}

mutation addPlaceMutation($place: PlaceInput!) {
  addPlaceMutation(place: $place) {
    id
    overview {
      name
      location
    }
  }
}
