service: serverless-graphql

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"

functions:
  api:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true
        response:
          headers:
            Access-Control-Allow-Origin: "*"
